### ISSUE TITLE
Can I use it without lock when slow producer and fast consumer? 

### ISSUE THREAD

**Issue by sankred9527** [AndersKaloer/Ring-Buffer#14]
If I have two thread , one is a very slow producer and another is a very fast consumer . 

Can I use your ringbuffer without lock ?  and  without any memory barrier  ?

**Comment by AndersKaloer** [comment]
You should not use the ring buffer from multiple threads without a lock. The speed of the producer/consumer does not change that.
Unless the threads are synchronized in some other way, using it without a lock will most likely result in failure at some point.
