### ISSUE TITLE
can it be used ?

### ISSUE THREAD

**Issue by ranshalit** [AndersKaloer/Ring-Buffer#2]
Hello,

Do you recommend using the ring buffer in other applications or is it not "used" enough yet ?

Thanks,
Ran

**Comment by AndersKaloer** [comment]
Hi Ran,

Sure, it can be used. I have used it in a couple of projects without any problems.
Obviously, I do not guarantee that it is bug free, and I will leave it completely up to you to decide whether to use it or not. In case you find a bug feel free to report it as an issue.
