### ISSUE TITLE
advise about readme

### ISSUE THREAD

**Issue by JQChris** [AndersKaloer/Ring-Buffer#7]
I am very interested in this demo。I tried to go through "Readme"for more details,but nothing in it。  
    Enrich the content of the document so that more readers learn more。
    A great demo.

**Comment by deeplyembeddedWP** [comment]
> ```
>  I am very interested in this demo。I tried to go through "Readme"for more details,but nothing in it。  
> Enrich the content of the document so that more readers learn more。
> A great demo.
> ```

I believe the source is well commented, hence there's no need for exhaustive documentation.
